### ISSUE TITLE
Error when tracing echelle orders in HARPS data

### ISSUE THREAD

**Issue by rickynilsson** [rabrahm/ceres#15]
I'm running into an issue in harpspipe.py:
```
Generating Master calibration frames...
		-> Masterbias: done!
		-> Masterflat: done!
	Tracing echelle orders...
Traceback (most recent call last):
  File "harpspipe.py", line 197, in <module>
    c_all1,nord_all1 = GLOBALutils.get_them(Flat[:,:,0],ext_aperture_B,trace_degree,mode=1)
  File "../utils/GLOBALutils/GLOBALutils.py", line 287, in get_them
    x = ejx[:pos[i]+exap2+1]
TypeError: slice indices must be integers or None or have an __index__ method
```
Is it just a bad FITS file?

**Comment by rickynilsson** [comment]
exap2 can end up being non-integer. Converted with int() like elsewhere in the get_them function.
