### ISSUE TITLE
import CCF error

### ISSUE THREAD

**Issue by sbrems** [rabrahm/ceres#19]
Dear Rafael et al.,

thank you for that very nice ceres pipeline.
I was using it for quite some time, however now I tried to install it on a new cluster and do not get it to run. Whenever I try to run it, I get the error that CCF is not defined. To be precise, here is the error:

$ python2 ferospipe.py /mnt/fhgfs/RVSPY/archival_datasearch_oct18/sciencefiles/HD111103/
Traceback (most recent call last):
  File "ferospipe.py", line 20, in <module>
    import ferosutils
  File "/data/beegfs/astro-storage/RVSPY/ceres/feros/ferosutils.py", line 16, in <module>
    import GLOBALutils
  File "../utils/GLOBALutils/GLOBALutils.py", line 23, in <module>
    import CCF
ImportError: No module named CCF

Thank you,
Stefan

**Comment by rabrahm** [comment]
Hi Stefan,

Usually that kind of messages mean that the associated code was not
properly compiled when installing CERES. Specifically, CCF is a fortan code
that should have created a CCF.o file in ceres/utils/CCF after the
installation.

Rafael

**Comment by nespinoza** [comment]
Hi Rafael, 

 We solved this with Stefan --- turns out the Fortran codes (`Proceso_f2py`) use `f2py` via `subprocess`, which in turn use the `f2py` installed by default which *might* be different than the python version used to run the install (e.g., an user with Python 3 by default, might use the pipeline with python2.7 by installing it in the computer, run the `install.py` code via '`python2.7 install.py`' and then the `subprocess` call in the `install.py` file will run `Proceso_f2py`, which uses `f2py` **_BUT_** from Python 3 by default). What I did was to simply replace the `f2py` call in `Proceso_f2py` by `f2py2.7` (which other `f2py` versions you have in your computer can be checked via `whois f2py`). Reminder to myself (or to you) to check which python version the user has by default to keep track of this? Add a warning? Perhaps at the very least put this in a FAQ in the README file.

Néstor
